# --- Main Colors ---
background            #0f1512
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #0f1512

selection_background  #7e9689
selection_foreground  #000000

url_color             #bbe2f6

# --- ANSI Colors ---
color0                #0f1512
color1                #ffd2cc
color2                #bbe2f6
color3                #c9e2d4
color4                #a1ecca
color5                #a6ccdf
color6                #b3ccbe
color7                #ffffff

color8                #404944
color9                #ff5449
color10               #7196a8
color11               #7e9689
color12               #569e80
color13               #253b31
color14               #113b4a
color15               #d5dfd8

# --- Starship Prompt Bubbles ---
color255              #569e80
color254              #a1ecca
color253              #7e9689
color252              #c9e2d4
color251              #7196a8
color250              #bbe2f6
color249              #ff5449
color248              #ffd2cc

color232              #000000
color233              #002c1e
color234              #000000
color235              #142a21
color236              #000000
color237              #002937
color238              #000000
color239              #540003
color240              #000000

# Matched with unthemed light/dark
color243              #a1ecca
color244              #ffd2cc
color245              #89938c

# --- UI Elements ---
active_tab_foreground   #002c1e
active_tab_background   #a1ecca
inactive_tab_foreground #000000
inactive_tab_background #569e80

active_border_color     #a1ecca
inactive_border_color   #abb4ae

# --- Marks ---
mark1_foreground        #00150c
mark1_background        #a7f2d0
mark2_foreground        #01150d
mark2_background        #cfe9da
mark3_foreground        #00131c
mark3_background        #c1e8fc
