background		#0f1512
foreground		#ffffff

cursor			#ffffff
cursor_text_color	#0f1512

selection_background	#7e9689
selection_foreground	#000000

url_color		#bbe2f6

color0			#0f1512
color8			#404944

color1			#ffd2cc
color9			#ff5449

color3			#c9e2d4
color10			#7e9689

color4			#a1ecca
color11			#569e80

color5			#dee4de
color12			#252b28

color6			#abb4ae
color13			#89938c

color7			#ffffff
color14			#d5dfd8
