# --- Main Colors ---
background            #191113
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #191113

selection_background  #aa8890
selection_foreground  #000000

url_color             #ffd4b1

# --- ANSI Colors ---
color0                #191113
color1                #ffd2cc
color2                #ffd4b1
color3                #fad2db
color4                #ffd0db
color5                #eebd93
color6                #e3bdc5
color7                #ffffff

color8                #514346
color9                #ff5449
color10               #b48862
color11               #aa8890
color12               #c67b91
color13               #492f36
color14               #4e2f10
color15               #ecd7db

# --- Starship Prompt Bubbles ---
color255              #c67b91
color254              #ffd0db
color253              #aa8890
color252              #fad2db
color251              #b48862
color250              #ffd4b1
color249              #ff5449
color248              #ffd2cc

color232              #000000
color233              #471226
color234              #000000
color235              #361f26
color236              #000000
color237              #3a1f03
color238              #000000
color239              #540003
color240              #000000

# Matched with unthemed light/dark
color243              #ffd0db
color244              #ffd2cc
color245              #9e8c8f

# --- UI Elements ---
active_tab_foreground   #471226
active_tab_background   #ffd0db
inactive_tab_foreground #000000
inactive_tab_background #c67b91

active_border_color     #ffd0db
inactive_border_color   #c0adb1

# --- Marks ---
mark1_foreground        #2b0011
mark1_background        #ffd9e1
mark2_foreground        #1f0b11
mark2_background        #ffd9e1
mark3_foreground        #1e0d00
mark3_background        #ffdcc0
