theme = "rose_pine"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"
scrolloff = 8
true-color = true  
undercurl = true

jump-label-alphabet = "hatesincludorkmjfxwypgvb"
end-of-line-diagnostics = "error"
rulers = [80, 120]
completion-replace = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
goto-reference-include-declaration = false
display-inlay-hints = true
display-progress-messages = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.smart-tab]
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "warning" 

